using URLShotenerV1.Entities;
using URLShotenerV1.Exceptions;
using URLShotenerV1.Repository;
using URLShotenerV1.Services;
using URLShotenerV1.Strategies;

//  UrlEntity
//              public string OriginalUrl { get; }      // No set as they are always set via constructor
//              public string ShortUrl { get; }
//              public DateTimeOffset? ExpirationTime { get; }
//              public DateTimeOffset CreatedDate { get; }
//              public DateTimeOffset? LastAccessed { get; private set; }
//              private int _totalClicks;
//              public int TotalClicks => _totalClicks;
//              void RecordVisit() -> _totalClicks++; LastAccessed = DateTimeOffset.UtcNow;
//              bool HasExpired() -> ExpirationTime.HasValue && ExpirationTime.Value < DateTimeOffset.UtcNow;
// UrlShortenerService -> This service is the core service that the 
//                        client will use to generate and fetch urls
//          depends on a IUrlRepository
//          depends on a IUrlGeneratorStrategy
//          string shortenUrl(longUrl, customAlias?, DateTimeOffset? ttl)
//              1. Check if any custom url has been provided.
//                  1.1 If yes then check if the custom alias is already taken or not.
//                          return AliasAlreadyTakenException
//                  1.2 If no then we can use this custom alias.
//              2. Generate short url using strategy.
//              3. Create the UrlEntity and store the mapping in repository.        
//          string redirectUrl(shortUrl)
//              1. If the short url is null or empty return InvalidShortUrlException
//              2. Check if the shortUrl exists in the repository.
//                  If not found return UrlNotFoundException.
//              3. Check if the shortUrl has expired =>  urlEntity.HasExpired()
//                  If yes then return UrlExpiredException
//              4. Record url visit (urlEntity.RecordVisit() )
//                 and Return the long url. 
//  IUrlRepository ->
//                  AddUrlEntity
//                  GetUrlEntity
//                  UpdateUrlEntity
//                  CustomUrlExists
//  


public class Program
{
    private static int _passed = 0;
    private static int _failed = 0;

    public static void Main()
    {
        Console.WriteLine("=== URLShortenerV1 Test Cases ===\n");

        // --- UrlEntity Tests ---
        Test_UrlEntity_Creation();
        Test_UrlEntity_RecordVisit_IncrementsClicks();
        Test_UrlEntity_IsExpired_ReturnsTrueForPastDate();
        Test_UrlEntity_IsExpired_ReturnsFalseForFutureDate();
        Test_UrlEntity_IsExpired_ReturnsFalseWhenNoExpiration();
        Test_UrlEntity_InvalidOriginalUrl_Throws();
        Test_UrlEntity_InvalidShortUrl_Throws();

        // --- Strategy Tests ---
        Test_Strategy_GeneratesUniqueAliases();
        Test_Strategy_GeneratesNonEmptyStrings();

        // --- Repository Tests ---
        Test_Repository_AddAndRetrieve();
        Test_Repository_DuplicateAlias_Throws();
        Test_Repository_NonExistentAlias_ReturnsNull();
        Test_Repository_ShortUrlExists();

        // --- Service Tests ---
        Test_Service_ShortenUrl_AutoGenerated();
        Test_Service_ShortenUrl_CustomAlias();
        Test_Service_ShortenUrl_DuplicateCustomAlias_Throws();
        Test_Service_RedirectUrl_Success();
        Test_Service_RedirectUrl_NotFound_Throws();
        Test_Service_RedirectUrl_Expired_Throws();
        Test_Service_RedirectUrl_InvalidUrl_Throws();
        Test_Service_RedirectUrl_IncrementsClickCount();

        Console.WriteLine($"\n=== Results: {_passed} passed, {_failed} failed ===");
    }

    // --- UrlEntity Tests ---

    static void Test_UrlEntity_Creation()
    {
        var entity = new UrlEntity("https://google.com", "abc", null);
        Assert(entity.OriginalUrl == "https://google.com", "UrlEntity_Creation: OriginalUrl set");
        Assert(entity.ShortUrl == "abc", "UrlEntity_Creation: ShortUrl set");
        Assert(entity.TotalClicks == 0, "UrlEntity_Creation: TotalClicks is 0");
        Assert(entity.LastAccessed == null, "UrlEntity_Creation: LastAccessed is null");
        Assert(entity.CreatedDate != default, "UrlEntity_Creation: CreatedDate is set");
    }

    static void Test_UrlEntity_RecordVisit_IncrementsClicks()
    {
        var entity = new UrlEntity("https://google.com", "abc", null);
        entity.RecordVisit();
        entity.RecordVisit();
        Assert(entity.TotalClicks == 2, "RecordVisit: TotalClicks incremented to 2");
        Assert(entity.LastAccessed != null, "RecordVisit: LastAccessed is set");
    }

    static void Test_UrlEntity_IsExpired_ReturnsTrueForPastDate()
    {
        var entity = new UrlEntity("https://google.com", "abc", DateTimeOffset.UtcNow.AddMinutes(-1));
        Assert(entity.IsExpired() == true, "IsExpired: true for past date");
    }

    static void Test_UrlEntity_IsExpired_ReturnsFalseForFutureDate()
    {
        var entity = new UrlEntity("https://google.com", "abc", DateTimeOffset.UtcNow.AddMinutes(10));
        Assert(entity.IsExpired() == false, "IsExpired: false for future date");
    }

    static void Test_UrlEntity_IsExpired_ReturnsFalseWhenNoExpiration()
    {
        var entity = new UrlEntity("https://google.com", "abc", null);
        Assert(entity.IsExpired() == false, "IsExpired: false when no expiration");
    }

    static void Test_UrlEntity_InvalidOriginalUrl_Throws()
    {
        bool threw = false;
        try { new UrlEntity("", "abc", null); }
        catch (ArgumentException) { threw = true; }
        Assert(threw, "UrlEntity: throws on empty originalUrl");
    }

    static void Test_UrlEntity_InvalidShortUrl_Throws()
    {
        bool threw = false;
        try { new UrlEntity("https://google.com", "  ", null); }
        catch (ArgumentException) { threw = true; }
        Assert(threw, "UrlEntity: throws on whitespace shortUrl");
    }

    // --- Strategy Tests ---

    static void Test_Strategy_GeneratesUniqueAliases()
    {
        var strategy = new CounterBasedBase62UrlGeneratorStrategy();
        var a1 = strategy.Generate("https://a.com");
        var a2 = strategy.Generate("https://b.com");
        Assert(a1 != a2, "Strategy: generates unique aliases");
    }

    static void Test_Strategy_GeneratesNonEmptyStrings()
    {
        var strategy = new CounterBasedBase62UrlGeneratorStrategy();
        var alias = strategy.Generate("https://a.com");
        Assert(!string.IsNullOrEmpty(alias), "Strategy: generates non-empty string");
    }

    // --- Repository Tests ---

    static void Test_Repository_AddAndRetrieve()
    {
        var repo = new InMemoryUrlRepository();
        var entity = new UrlEntity("https://google.com", "g1", null);
        repo.AddUrlEntity(entity);
        var retrieved = repo.GetEntityByAlias("g1");
        Assert(retrieved != null && retrieved.OriginalUrl == "https://google.com", "Repository: add and retrieve");
    }

    static void Test_Repository_DuplicateAlias_Throws()
    {
        var repo = new InMemoryUrlRepository();
        repo.AddUrlEntity(new UrlEntity("https://a.com", "dup", null));
        bool threw = false;
        try { repo.AddUrlEntity(new UrlEntity("https://b.com", "dup", null)); }
        catch (AliasAlreadyTakenException) { threw = true; }
        Assert(threw, "Repository: duplicate alias throws");
    }

    static void Test_Repository_NonExistentAlias_ReturnsNull()
    {
        var repo = new InMemoryUrlRepository();
        Assert(repo.GetEntityByAlias("nope") == null, "Repository: non-existent alias returns null");
    }

    static void Test_Repository_ShortUrlExists()
    {
        var repo = new InMemoryUrlRepository();
        repo.AddUrlEntity(new UrlEntity("https://a.com", "exists", null));
        Assert(repo.ShortUrlExists("exists") == true, "Repository: ShortUrlExists true");
        Assert(repo.ShortUrlExists("nope") == false, "Repository: ShortUrlExists false");
    }

    // --- Service Tests ---

    static UrlShortenerService CreateService()
    {
        return new UrlShortenerService(new InMemoryUrlRepository(), new CounterBasedBase62UrlGeneratorStrategy());
    }

    static void Test_Service_ShortenUrl_AutoGenerated()
    {
        var service = CreateService();
        var alias = service.ShortenUrl("https://google.com", null);
        Assert(!string.IsNullOrEmpty(alias), "Service: ShortenUrl auto-generates alias");
    }

    static void Test_Service_ShortenUrl_CustomAlias()
    {
        var service = CreateService();
        var alias = service.ShortenUrl("https://google.com", "myalias");
        Assert(alias == "myalias", "Service: ShortenUrl uses custom alias");
    }

    static void Test_Service_ShortenUrl_DuplicateCustomAlias_Throws()
    {
        var service = CreateService();
        service.ShortenUrl("https://a.com", "taken");
        bool threw = false;
        try { service.ShortenUrl("https://b.com", "taken"); }
        catch (AliasAlreadyTakenException) { threw = true; }
        Assert(threw, "Service: duplicate custom alias throws");
    }

    static void Test_Service_RedirectUrl_Success()
    {
        var service = CreateService();
        service.ShortenUrl("https://google.com", "g");
        var result = service.RedirectUrl("g");
        Assert(result == "https://google.com", "Service: RedirectUrl returns original URL");
    }

    static void Test_Service_RedirectUrl_NotFound_Throws()
    {
        var service = CreateService();
        bool threw = false;
        try { service.RedirectUrl("nonexistent"); }
        catch (UrlNotFoundException) { threw = true; }
        Assert(threw, "Service: RedirectUrl throws when not found");
    }

    static void Test_Service_RedirectUrl_Expired_Throws()
    {
        var service = CreateService();
        service.ShortenUrl("https://google.com", "exp", DateTimeOffset.UtcNow.AddMilliseconds(-1));
        bool threw = false;
        try { service.RedirectUrl("exp"); }
        catch (UrlExpiredException) { threw = true; }
        Assert(threw, "Service: RedirectUrl throws when expired");
    }

    static void Test_Service_RedirectUrl_InvalidUrl_Throws()
    {
        var service = CreateService();
        bool threw = false;
        try { service.RedirectUrl(""); }
        catch (InvalidShortUrlException) { threw = true; }
        Assert(threw, "Service: RedirectUrl throws on empty url");
    }

    static void Test_Service_RedirectUrl_IncrementsClickCount()
    {
        var repo = new InMemoryUrlRepository();
        var service = new UrlShortenerService(repo, new CounterBasedBase62UrlGeneratorStrategy());
        service.ShortenUrl("https://google.com", "clicks");
        service.RedirectUrl("clicks");
        service.RedirectUrl("clicks");
        var entity = repo.GetEntityByAlias("clicks");
        Assert(entity != null && entity.TotalClicks == 2, "Service: RedirectUrl increments click count");
    }

    // --- Helper ---

    static void Assert(bool condition, string testName)
    {
        if (condition)
        {
            Console.WriteLine($"  [PASS] {testName}");
            _passed++;
        }
        else
        {
            Console.WriteLine($"  [FAIL] {testName}");
            _failed++;
        }
    }
}
